### ISSUE TITLE
Failure during installation - missing dependency

### ISSUE THREAD

**Issue by magick93** [goalgorilla/drupal_social#309]
Hello

I'm trying to install OpenSocial on OpenShift. In theory this should work, but I'm running into some problems. 

I appreciate that you are probably not able to give advice on the matters relating to OpenShift, but perhaps you can see what or where the problem is.

# Using Php 7 OpenShift template

1. In OpenShift, click on `Add to Project` > `PHP` > `Version 7.0`. *![image](https://cloud.githubusercontent.com/assets/2173213/24243712/5321c8ea-0fbc-11e7-9e8e-f19af61fe8db.png)*
*This uses a S2I container to build a PHP application. The S2I is located at https://github.com/sclorg/s2i-php-container/blob/master/7.0/README.md

NB: I also tried using Php 5.6 but go exactly the same error.

2. Add the OpenSocial Git repository. 
![image](https://cloud.githubusercontent.com/assets/2173213/24243778/8d901900-0fbc-11e7-83c9-d849151ac215.png)

The installation logs are:

```
Cloning "https://github.com/goalgorilla/drupal_social.git" ...
	Commit:	847ef5fee6a9bfe7d99807c40adc84f25c238cd6 (Add the possibility to add a local docker-compose.override.yml file)
	Author:	Jochem van Nieuwenhuijsen <jochem@goalgorilla.com>
	Date:	Tue Feb 14 16:06:47 2017 +0100
---> Installing application source...
Found 'composer.json', installing dependencies using composer.phar...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  298k  100  298k    0     0   970k      0 --:--:-- --:--:-- --:--:--  972k
All settings correct for using Composer
Downloading...
Composer (version 1.4.1) successfully installed to: /opt/app-root/src/composer.phar
Use it: php composer.phar
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 158 installs, 0 updates, 0 removals
  - Installing drupal-composer/drupal-scaffold (2.2.0): Downloading (100%)
  - Installing cweagans/composer-patches (1.6.0): Downloading (100%)
No patches supplied.
Gathering patches for dependencies. This might take a minute.
  - Installing composer/installers (v1.2.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing clue/stream-filter (v1.3.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing psr/http-message (1.0.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing php-http/message-factory (v1.0.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing php-http/message (1.5.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing php-http/discovery (1.2.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing php-http/promise (v1.0.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing php-http/httplug (v1.1.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing php-http/curl-client (v1.7.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing league/csv (7.2.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing happyr/linkedin-api-client (1.0.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing guzzlehttp/guzzle (6.2.3): Downloading (100%)
Patches already gathered. Skipping
  - Installing phpseclib/phpseclib (2.0.4): Downloading (100%)
Patches already gathered. Skipping
  - Installing psr/log (1.0.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing monolog/monolog (1.22.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing firebase/php-jwt (v4.0.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing google/apiclient-services (v0.9): Downloading (100%)
Patches already gathered. Skipping
  - Installing psr/cache (1.0.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing google/auth (v0.11.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing google/apiclient (v2.1.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing facebook/graph-sdk (5.4.4): Downloading (100%)
Patches already gathered. Skipping
  - Installing zendframework/zend-stdlib (3.1.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing zendframework/zend-escaper (2.5.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing zendframework/zend-feed (2.7.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing zendframework/zend-diactoros (1.3.10): Downloading (100%)
Patches already gathered. Skipping
  - Installing twig/twig (v1.33.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/yaml (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/polyfill-mbstring (v1.3.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/translation (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/validator (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing ircmaxell/password-compat (v1.0.4): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/polyfill-php55 (v1.3.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/serializer (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/routing (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/polyfill-php54 (v1.3.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/http-foundation (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/psr-http-message-bridge (v0.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/process (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/polyfill-iconv (v1.3.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/debug (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/event-dispatcher (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/http-kernel (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/dependency-injection (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/console (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/polyfill-apcu (v1.3.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/class-loader (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony-cmf/routing (1.4.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing stack/builder (v1.0.4): Downloading (100%)
Patches already gathered. Skipping
  - Installing paragonie/random_compat (v2.0.10): Downloading (100%)
Patches already gathered. Skipping
  - Installing masterminds/html5 (2.2.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing doctrine/lexer (v1.0.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing egulias/email-validator (1.2.14): Downloading (100%)
Patches already gathered. Skipping
  - Installing easyrdf/easyrdf (0.9.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing doctrine/inflector (v1.1.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing doctrine/collections (v1.4.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing doctrine/cache (v1.6.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing doctrine/annotations (v1.2.7): Downloading (100%)
Patches already gathered. Skipping
  - Installing doctrine/common (v2.5.3): Downloading (100%)
Patches already gathered. Skipping
  - Installing composer/semver (1.4.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing asm89/stack-cors (1.0.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/core (8.2.7): Downloading (100%)
- Applying patches for drupal/core
https://www.drupal.org/files/issues/2724283-block-22.patch (Fix region string issue)
https://www.drupal.org/files/issues/2369119-120.patch (Make sure exposed filters work)
https://www.drupal.org/files/issues/728702-163.patch (Redirect to install.php on empty DB)
https://www.drupal.org/files/issues/2687773-18-Cleanup-user-input-for-checkboxes-8.2.patch (Clean up user input for exposed checkboxes)
https://www.drupal.org/files/issues/2744069-5-views-in-queries.patch (views_query_views_alter does not handle IN queries)
https://www.drupal.org/files/issues/color-optional-html-preview-2844190-2.patch (Color module html preview optional)
Patches already gathered. Skipping
  - Installing sebastian/version (1.0.6): Downloading (100%)
Patches already gathered. Skipping
  - Installing sebastian/recursion-context (1.0.5): Downloading (100%)
Patches already gathered. Skipping
  - Installing sebastian/global-state (1.1.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing sebastian/exporter (1.2.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing sebastian/environment (1.3.8): Downloading (100%)
Patches already gathered. Skipping
  - Installing sebastian/diff (1.4.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing sebastian/comparator (1.2.4): Downloading (100%)
Patches already gathered. Skipping
  - Installing doctrine/instantiator (1.0.5): Downloading (100%)
Patches already gathered. Skipping
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing phpunit/phpunit-mock-objects (2.3.8): Downloading (100%)
Patches already gathered. Skipping
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)
Patches already gathered. Skipping
  - Installing phpunit/php-token-stream (1.4.11): Downloading (100%)
Patches already gathered. Skipping
  - Installing phpunit/php-file-iterator (1.4.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing phpunit/php-code-coverage (2.2.4): Downloading (100%)
Patches already gathered. Skipping
  - Installing mikey179/vfsstream (v1.6.4): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/css-selector (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/dom-crawler (v3.2.6): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/browser-kit (v3.2.6): Downloading (100%)
Patches already gathered. Skipping
  - Installing fabpot/goutte (v3.2.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/finder (v2.8.18): Downloading (100%)
Patches already gathered. Skipping
  - Installing behat/mink (v1.7.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing behat/mink-browserkit-driver (v1.3.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing behat/mink-goutte-driver (v1.2.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing webmozart/assert (1.2.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing phpdocumentor/reflection-docblock (2.0.4): Downloading (100%)
Patches already gathered. Skipping
  - Installing phpspec/prophecy (v1.7.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/votingapi (3.0.0-alpha2): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/token (1.0.0-rc1): Downloading (100%)
Patches already gathered. Skipping
  - Installing hybridauth/hybridauth (v2.8.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/social_api (1.0.0-beta2): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/social_auth (1.0.0-beta3): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/search_api (1.0.0-beta4): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/r4032login (dev-1.x 391f10d): Cloning 391f10d69b
Patches already gathered. Skipping
  - Installing drupal/entity (1.0.0-alpha3): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/profile (1.0.0-alpha5): Downloading (100%)
- Applying patches for drupal/profile
https://www.drupal.org/files/issues/profile-accesscontrol-2703825-6.patch (Fixes access control on entities)
Patches already gathered. Skipping
  - Installing drupal/override_node_options (2.0.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/message (1.0.0-alpha4): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/like_and_dislike (1.0.0-alpha2): Downloading (100%)
- Applying patches for drupal/like_and_dislike
https://www.drupal.org/files/issues/2848080-2-preview-fails-on-node.patch (Fix preview on node)
Patches already gathered. Skipping
  - Installing drupal/libraries (dev-3.x 061ead0): Cloning 061ead081c
Patches already gathered. Skipping
  - Installing drupal/crop (1.0.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/image_widget_crop (1.4.0): Downloading (100%)
- Applying patches for drupal/image_widget_crop
https://www.drupal.org/files/issues/always_expand_crop_area-2826494-6.patch (Always expand crop area not working as expected)
Patches already gathered. Skipping
  - Installing drupal/group (1.0.0-beta4): Downloading (100%)
- Applying patches for drupal/group
https://www.drupal.org/files/issues/error-when-uploading-files-2793621-5.patch (Fix fatal error when uploading files for group)
Patches already gathered. Skipping
  - Installing drupal/flag (dev-4.x 4cc5894): Cloning 4cc5894d7e
Patches already gathered. Skipping
  - Installing drupal/field_group (1.0.0-rc6): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/config_update (1.3.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/features (3.5.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/dynamic_entity_reference (1.0.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/devel (1.0.0-rc1): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/csv_serialization (1.0.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/bootstrap (3.1.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/admin_toolbar (1.18.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/addtoany (1.7.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing commerceguys/enum (v1.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing commerceguys/addressing (v1.0.0-beta2): Downloading (100%)
Patches already gathered. Skipping
  - Installing commerceguys/zone (dev-master 36fe2e8): Cloning 36fe2e8f5a
Patches already gathered. Skipping
  - Installing commerceguys/intl (v0.7.4): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/address (1.0.0-rc4): Downloading (100%)
Patches already gathered. Skipping
  - Installing abraham/twitteroauth (0.7.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing goalgorilla/open_social (dev-8.x-1.x 257729c): Cloning 257729c5dc
Patches already gathered. Skipping
  - Installing goalgorilla/open_social_scripts (dev-master ed6d972): Cloning ed6d9728de
Patches already gathered. Skipping
  - Installing phpunit/phpunit (4.8.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing webmozart/path-util (2.3.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/var-dumper (v2.8.17): Downloading (100%)
Patches already gathered. Skipping
  - Installing jakub-onderka/php-console-color (0.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing dnoegel/php-xdg-base-dir (0.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing nikic/php-parser (v3.0.5): Downloading (100%)
Patches already gathered. Skipping
  - Installing psy/psysh (v0.8.3): Downloading (100%)
Patches already gathered. Skipping
  - Installing pear/console_table (v1.3.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing consolidation/output-formatters (3.1.8): Downloading (100%)
Patches already gathered. Skipping
  - Installing consolidation/annotated-command (2.4.7): Downloading (100%)
Patches already gathered. Skipping
  - Installing squizlabs/php_codesniffer (2.8.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing drush/drush (8.1.10): Downloading (100%)
Patches already gathered. Skipping
  - Installing jcalderonzumba/gastonjs (v1.0.3): Downloading (100%)
Patches already gathered. Skipping
  - Installing jcalderonzumba/mink-phantomjs-driver (v0.3.3): Downloading (100%)
Patches already gathered. Skipping
  - Installing psr/container (1.0.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/drupal-driver (v1.2.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/filesystem (v3.2.6): Downloading (100%)
Patches already gathered. Skipping
  - Installing symfony/config (v3.2.6): Downloading (100%)
Patches already gathered. Skipping
  - Installing container-interop/container-interop (1.2.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing behat/transliterator (v1.1.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing behat/gherkin (v4.4.5): Downloading (100%)
Patches already gathered. Skipping
  - Installing behat/behat (v3.3.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing behat/mink-extension (v2.2): Downloading (100%)
Patches already gathered. Skipping
  - Installing instaclick/php-webdriver (1.4.3): Downloading (100%)
Patches already gathered. Skipping
  - Installing behat/mink-selenium2-driver (v1.3.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/drupal-extension (v3.1.5): Downloading (100%)
Patches already gathered. Skipping
  - Installing drupal/coder (8.2.12): Downloading (100%)
Patches already gathered. Skipping
  - Installing pdepend/pdepend (2.1.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing phpmd/phpmd (2.5.0): Downloading (100%)
Patches already gathered. Skipping
  - Installing theseer/fdomdocument (1.6.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing sebastian/finder-facade (1.2.1): Downloading (100%)
Patches already gathered. Skipping
  - Installing sebastian/phpcpd (2.0.4): Downloading (100%)
php-http/message suggests installing slim/slim (Used with Slim Framework PSR-7 implementation)
php-http/discovery suggests installing puli/composer-plugin (Sets up Puli which is recommended for Discovery to work. Check http://docs.php-http.org/en/latest/discovery.html for more details.)
phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
phpseclib/phpseclib suggests installing ext-mcrypt (Install the Mcrypt extension in order to speed up a few other cryptographic operations.)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
google/apiclient suggests installing cache/filesystem-adapter (For caching certs and tokens (using Google_Client::setCache))
zendframework/zend-feed suggests installing zendframework/zend-cache (Zend\Cache component, for optionally caching feeds between requests)
zendframework/zend-feed suggests installing zendframework/zend-db (Zend\Db component, for use with PubSubHubbub)
zendframework/zend-feed suggests installing zendframework/zend-http (Zend\Http for PubSubHubbub, and optionally for use with Zend\Feed\Reader)
zendframework/zend-feed suggests installing zendframework/zend-servicemanager (Zend\ServiceManager component, for easily extending ExtensionManager implementations)
zendframework/zend-feed suggests installing zendframework/zend-validator (Zend\Validator component, for validating email addresses used in Atom feeds and entries ehen using the Writer subcomponent)
symfony/validator suggests installing symfony/expression-language (For using the 2.4 Expression validator)
symfony/validator suggests installing symfony/intl ()
symfony/validator suggests installing symfony/property-access (For using the 2.4 Validator API)
symfony/serializer suggests installing symfony/property-access (For using the ObjectNormalizer.)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
easyrdf/easyrdf suggests installing ml/json-ld (~1.0)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
behat/mink suggests installing behat/mink-zombie-driver (fast and JS-enabled headless driver for any app (requires node.js))
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
commerceguys/addressing suggests installing symfony/intl (to use it as the source of country data)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
symfony/var-dumper suggests installing ext-symfony_debug ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
pear/console_table suggests installing pear/Console_Color2 (>=0.1.2)
drush/drush suggests installing drush/config-extra (Provides configuration workflow commands, such as config-merge.)
behat/behat suggests installing behat/symfony2-extension (for integration with Symfony2 web framework)
behat/behat suggests installing behat/yii-extension (for integration with Yii web framework)
Writing lock file
Generating optimized autoload files
Warning: Ambiguous class resolution, "Drupal\Component\Utility\Random" was found in both "$baseDir . '/html/core/lib/Drupal/Component/Utility/Random.php" and "/opt/app-root/src/vendor/drupal/drupal-driver/src/Drupal/Component/Utility/Random.php", the first will be used.
Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)> DrupalComposer\DrupalScaffold\Plugin::scaffold
Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)Downloading (connecting...)Downloading (0%)           Downloading (100%)
Pushing image 172.30.1.1:5000/priceinsight/opensocial:latest ...
Pushed 0/9 layers, 0% complete
Pushed 0/9 layers, 11% complete
Pushed 1/9 layers, 11% complete
Push successful
```

3. Set the Deployment Config to use the Environment Variable `DOCUMENTROOT` to have the value `/html` for the Deployment Config.

## Errors

The installation screen loads, but during installation it fails with:

`[Thu Mar 23 10:24:21.698880 2017] [:error] [pid 28] [client 172.17.0.1:50364] Drupal\\Core\\Config\\UnmetDependenciesException: Configuration objects (features.bundle.social) provided by social have unmet dependencies in /opt/app-root/src/html/core/lib/Drupal/Core/Config/UnmetDependenciesException.php on line 84 #0 /opt/app-root/src/html/core/lib/Drupal/Core/Config/ConfigInstaller.php(460): Drupal\\Core\\Config\\UnmetDependenciesException::create('social', Array)\n#1 /opt/app-root/src/html/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132): Drupal\\Core\\Config\\ConfigInstaller->checkConfigurationToInstall('module', 'social')\n#2 /opt/app-root/src/html/core/lib/Drupal/Core/Extension/ModuleInstaller.php(141): Drupal\\Core\\ProxyClass\\Config\\ConfigInstaller->checkConfigurationToInstall('module', 'social')\n#3 /opt/app-root/src/html/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, false)\n#4 /opt/app-root/src/html/core/includes/install.core.inc(1571): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, false)\n#5 /opt/app-root/src/html/core/includes/install.core.inc(661): install_install_profile(Array)\n#6 /opt/app-root/src/html/core/includes/install.core.inc(539): install_run_task(Array, Array)\n#7 /opt/app-root/src/html/core/includes/install.core.inc(116): install_run_tasks(Array)\n#8 /opt/app-root/src/html/core/install.php(44): install_drupal(Object(Composer\\Autoload\\ClassLoader))\n#9 {main}, referer:[ http://opensocial-priceinsight.myip.xip.io/core/install.php?rewrite=ok&profile=social&langcode=en](http://opensocial-priceinsight.myip.xip.io/core/install.php?rewrite=ok&profile=social&langcode=en)`

**Comment by ronaldtebrake** [comment]
Marking this closed as it's duplicate: 
https://www.drupal.org/project/social/issues/2863252
